version: 1.0
publish: app
services:
  app:
    image: react-weights:latest
    environment:
      NODE_ENV: production
      DEBUG: app:*
      APP_PW: test
      DB_NAME: weightbuddy
      DB_CONNECTION: mongodb://mongo
    command: npm run start
    ports:
      - container: 3001
        public: 80
    depends_on: 
      - mongo
    links:
      - mongo
  mongo:
    image: mongo