version: 1.0
publish: app
services:
  app:
    command: node index.js
    environment:
      debug: 'app:*'
      app_password: 'testing'
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 3000
        public: 80
    volumes:
      - .:app/
      - node_modules:app/node_modules