version: 1.0
publish: app
services:
  app:
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    environment:
      debug: 'app:*'
      app_password: 'testing'
    ports:
      - container: 3000
        public: 80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start