version: 1.0
publish: app
services:
  app:
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    environment:
      debug: 'app:*'
      app_password: 'testing'
    command: npm run start
    ports:
      - container: 3000
        public: 80